version: '3'
services:
  pythonscript:
    build:
      context: ./dockerfile_list
      dockerfile: Dockerfile_kaggle

    container_name: Kaggle
    volumes:
      - /home/ryuichi/.bashrc:/root/.bashrc:ro
      - /home/ryuichi/.vimrc:/root/.vimrc:ro
      - /home/ryuichi/.bashrc:/home/jupyter/.bashrc:ro
      - /home/ryuichi/.vimrc:/root/vimrc:ro
      - /home/ryuichi/.ssh:/root/.ssh:ro
      - /home/ryuichi/.kaggle/kaggle.json:/root/.kaggle/kaggle.json:ro
      - /home/ryuichi/kaggle/competition/2021_05_Outdoor:/work            
#      - /etc/passwd:/etc/passwd:ro
#      - /etc/group:/etc/group:ro
    working_dir: /work  
    user: 1000:1000
    security_opt:
      - seccomp:unconfined
    ports:
      - 9000:8888
    command: jupyter notebook --ip=0.0.0.0 --allow-root --no-browser
    environment:
       PYTHONPATH: "/work/src"

