FROM jupyter/datascience-notebook:lab-3.0.7

USER root

RUN apt-get update

#RUN pip install numpy


### setting 
#COPY /home/ryuichi/.kaggle/kaggle.json /root/.kaggle/kaggle.json
#COPY /home/ryuichi/.vimrc /root/.vimrc
#COPY /home/ryuichi/.bashrc /root/.bashrc
